float32[3] position         # Position in meters.               Frame of reference defined by local_frame.
float32[3] velocity                # Linear velocity in meters/second. Frame of reference defined by local_frame.
float32[3] acceleration                # Linear accel in meters/second^2.  Frame of reference defined by local_frame.
float32[4] q                # Quaternion rotation from FRD body frame to reference frame.
float32[3] angular_velocity                # Angular velocity in radians/second. Frame of reference defined by local_frame.